# Goal
geometry_msgs/PoseStamped destination
---
# Result
int32 code
string message

int32 SUCCESS=0
int32 CANCELED=1
int32 PLANNING_FAILED=2
int32 INVALID_STATE=3
---
# Feedback
float32 distance_remaining
string state
string status_message
